# 市場データのカラム名
DATE = "日付"
COMPANY_CODE = "コード"
COMPANY_NAME = "銘柄名"
MARKET_CATEGORY = "市場・商品区分"
INDUSTRY_CODE_33 = "33業種コード"
INDUSTRY_CATEGORY_33 = "33業種区分"
INDUSTRY_CODE_17 = "17業種コード"
INDUSTRY_CATEGORY_17 = "17業種区分"
SCALE_CODE = "規模コード"
SCALE_CATEGORY = "規模区分"

## 規模
TOPIX_CORE30 = "TOPIX Core30"
TOPIX_LARGE70 = "TOPIX Large70"
TOPIX_MID400 = "TOPIX Mid400"
TOPIX_SMALL1 = "TOPIX Small 1"
TOPIX_SMALL2 = "TOPIX Small 2"
OTHER = "-"
ALL_SCALE_CATEGORY_LIST = [
    TOPIX_CORE30,
    TOPIX_LARGE70,
    TOPIX_MID400,
    TOPIX_SMALL1,
    TOPIX_SMALL2,
    OTHER,
]
ALL_SCALE_CATEGORY = "すべて"
LEARGE_SCALE_CATEGORY = "大規模"
MIDDLE_SCALE_CATEGORY = "中規模"
SMALL_SCALE_CATEGORY = "小規模"
OTHER_SCALE_CATEGORY = "その他"
SCALE_CATEGORY_DICT = {
    ALL_SCALE_CATEGORY: ALL_SCALE_CATEGORY,
    LEARGE_SCALE_CATEGORY: [TOPIX_CORE30, TOPIX_LARGE70],
    MIDDLE_SCALE_CATEGORY: [TOPIX_MID400],
    SMALL_SCALE_CATEGORY: [TOPIX_SMALL1, TOPIX_SMALL2],
    OTHER_SCALE_CATEGORY: [OTHER],
}

## 業種
OTHER_PRODUCTS = "その他製品"
OTHER_FINANCE = "その他金融業"
GLASS_STONE_PRODUCTS = "ガラス・土石製品"
RUBBER_PRODUCTS = "ゴム製品"
SERVICE_INDUSTRY = "サービス業"
PULP_PAPER = "パルプ・紙"
REAL_ESTATE = "不動産業"
INSURANCE = "保険業"
WAREHOUSING_TRANSPORT = "倉庫・運輸関連業"
CHEMICALS = "化学"
PHARMACEUTICALS = "医薬品"
WHOLESALE = "卸売業"
RETAIL = "小売業"
CONSTRUCTION = "建設業"
INFORMATION_COMMUNICATION = "情報・通信業"
MACHINERY = "機械"
FISHERY_FORESTRY_AGRICULTURE = "水産・農林業"
SHIPPING = "海運業"
OIL_COAL_PRODUCTS = "石油・石炭製品"
AIR_TRANSPORT = "空運業"
PRECISION_MACHINERY = "精密機器"
TEXTILES = "繊維製品"
SECURITIES_COMMODITIES_FUTURES = "証券、商品先物取引業"
TRANSPORTATION_EQUIPMENT = "輸送用機器"
METAL_PRODUCTS = "金属製品"
IRON_STEEL = "鉄鋼"
MINING = "鉱業"
BANKING = "銀行業"
LAND_TRANSPORT = "陸運業"
ELECTRIC_GAS = "電気・ガス業"
ELECTRICAL_EQUIPMENT = "電気機器"
NONFERROUS_METALS = "非鉄金属"
FOOD_PRODUCTS = "食料品"
INDUSTRY_CATEGORY_DICT = {
    OTHER_PRODUCTS: [OTHER_PRODUCTS, OTHER],
    OTHER_FINANCE: [OTHER_FINANCE],
    GLASS_STONE_PRODUCTS: [GLASS_STONE_PRODUCTS],
    RUBBER_PRODUCTS: [RUBBER_PRODUCTS],
    SERVICE_INDUSTRY: [SERVICE_INDUSTRY],
    PULP_PAPER: [PULP_PAPER],
    REAL_ESTATE: [REAL_ESTATE],
    INSURANCE: [INSURANCE],
    WAREHOUSING_TRANSPORT: [WAREHOUSING_TRANSPORT],
    CHEMICALS: [CHEMICALS],
    PHARMACEUTICALS: [PHARMACEUTICALS],
    WHOLESALE: [WHOLESALE],
    RETAIL: [RETAIL],
    CONSTRUCTION: [CONSTRUCTION],
    INFORMATION_COMMUNICATION: [INFORMATION_COMMUNICATION],
    MACHINERY: [MACHINERY],
    FISHERY_FORESTRY_AGRICULTURE: [FISHERY_FORESTRY_AGRICULTURE],
    SHIPPING: [SHIPPING],
    OIL_COAL_PRODUCTS: [OIL_COAL_PRODUCTS],
    AIR_TRANSPORT: [AIR_TRANSPORT],
    PRECISION_MACHINERY: [PRECISION_MACHINERY],
    TEXTILES: [TEXTILES],
    SECURITIES_COMMODITIES_FUTURES: [SECURITIES_COMMODITIES_FUTURES],
    TRANSPORTATION_EQUIPMENT: [TRANSPORTATION_EQUIPMENT],
    METAL_PRODUCTS: [METAL_PRODUCTS],
    IRON_STEEL: [IRON_STEEL],
    MINING: [MINING],
    BANKING: [BANKING],
    LAND_TRANSPORT: [LAND_TRANSPORT],
    ELECTRIC_GAS: [ELECTRIC_GAS],
    ELECTRICAL_EQUIPMENT: [ELECTRICAL_EQUIPMENT],
    NONFERROUS_METALS: [NONFERROUS_METALS],
    FOOD_PRODUCTS: [FOOD_PRODUCTS],
}

# 市場データのcsvファイル名
MARKET_CSV_FILENAME = "market.csv"

# 無尽蔵の株価データのカラム名
MARKET_CODE = "市場コード"
OPEN_PRICE = "始値"
HIGH_PRICE = "高値"
LOW_PRICE = "安値"
CLOSE_PRICE = "終値"
VOLUME = "出来高"
STOCK_PRICE_COLUMNS = [
    DATE,
    COMPANY_CODE,
    MARKET_CODE,
    COMPANY_NAME,
    OPEN_PRICE,
    HIGH_PRICE,
    LOW_PRICE,
    CLOSE_PRICE,
    VOLUME,
    MARKET_CATEGORY,
]

# 株価データのcsvファイル名
STOCK_PRICE_CSV_FILENAME = "stock_price.csv"

# 業績データのcsvファイル名
FY_BALANCE_SHEET_CSV_FILENAME = "fy-balance-sheet.csv"
FY_CASH_FLOW_STATEMENT_CSV_FILENAME = "fy-cash-flow-statement.csv"
FY_PROFIT_AND_LOSS_CSV_FILENAME = "fy-profit-and-loss.csv"
FY_STOCK_DIVIDEND_CSV_FILENAME = "fy-stock-dividend.csv"
FY_ALL_CSV_FILENAME = "fy-data-all.csv"

FY_CSV_FILENAMES = [
    FY_BALANCE_SHEET_CSV_FILENAME,
    FY_CASH_FLOW_STATEMENT_CSV_FILENAME,
    FY_PROFIT_AND_LOSS_CSV_FILENAME,
    FY_STOCK_DIVIDEND_CSV_FILENAME,
]

# 財務データのカラム名
FISCAL_YEAR = "年度"
REVENUE = "売上高"
OPERATING_PROFIT = "営業利益"
OPERATING_PROFIT_MARGIN = "営業利益率"
ORDINARY_PROFIT = "経常利益"
NET_PROFIT = "純利益"
EPS = "EPS"
ROE = "ROE"
ROA = "ROA"
TOTAL_ASSETS = "総資産"
NET_ASSETS = "純資産"
SHAREHOLDER_EQUITY = "株主資本"
RETAINED_EARNINGS = "利益剰余金"
SHORT_TERM_DEBT = "短期借入金"
LONG_TERM_DEBT = "長期借入金"
BPS = "BPS"
EQUITY_RATIO = "自己資本比率"
OPERATING_CASH_FLOW = "営業CF"
INVESTING_CASH_FLOW = "投資CF"
FINANCING_CASH_FLOW = "財務CF"
CAPITAL_EXPENDITURE = "設備投資"
CASH_EQUIVALENTS = "現金同等物"
OPERATING_CASH_FLOW_MARGIN = "営業CFマージン"
DIVIDEND_PER_SHARE = "一株配当"
SURPLUS_FUNDS_DIVIDENDS = "剰余金の配当"
SHARE_BUYBACKS = "自社株買い"
DIVIDEND_PAYOUT_RATIO = "配当性向"
TOTAL_PAYOUT_RATIO = "総還元性向"
NET_ASSETS_PAYOUT_RATIO = "純資産配当率"


# 企業業績のカラム
DIVIDEND_YIELD = "配当利回り"
DIVIDEND_INCREASE_CONTINUOUS = "連続増配"
REVENUE_GRAD = "売上の勾配"
EPS_GRAD = "EPSの勾配"
BPS_GRAD = "BPSの勾配"
DIVIDEND_PER_SHARE_GRAD = "1株配当の勾配"
OPERATING_CASH_FLOW_GRAD = "営業CFの勾配"
CASH_EQUIVALENTS_GRAD = "現金同等物の勾配"
TOTAL_ASSETS_CASH_RATIO_GRAD = "総資産現金率の勾配"
OPERATING_CASH_FLOW_SURPLUS_EVERY_YEAR = "営業CFが毎年黒字"
CONTINUOUS_DIVIDEND_YEARS_AVG = "配当継続年数の平均値"
OPERATING_PROFIT_MARGIN_AVG = "営業利益率の平均値"
EQUITY_RATIO_AVG = "自己資本比率の平均値"
TOTAL_ASSETS_CASH_RATIO_AVG = "総資産現金率の平均値"
CURRENT_RATIO_AVG = "流動比率の平均値"
DIVIDEND_PAYOUT_RATIO_AVG = "配当性向の平均値"
ROE_AVG = "ROEの平均値"
ROA_AVG = "ROAの平均値"
PER = "PER"
PSR = "PSR"
PBR = "PBR"

PERFORMANCE_CSV_FILENAME = "peformance.csv"
STOCK_PRICE = "株価"


# フォルダ名とファイル名
DATA_DIRNAME = "data"

ENCODING = "utf-8"
